help_function () {
  echo "Commandes disponibles :"
  echo "  help : Affiche l'aide"
  echo "  ls : Liste les fichiers et répertoires"
  echo "  rm : Supprime un fichier"
  echo "  rmd : Supprime un répertoire vide"
  echo "  about : Affiche des informations sur le prompt"
  echo "  version : Affiche la version du prompt"
  echo "  age : Vérifie si l'utilisateur est majeur ou mineur"
  echo "  profil : Affiche le profil de l'utilisateur"
  echo "  cd : Change le répertoire courant"
  echo "  pwd : Affiche le répertoire courant"
  echo "  hour : Affiche l'heure actuelle"
  echo "  httpget : Télécharge une page web et l'enregistre dans un fichier HTML"
  echo "  clear : Efface l'écran"
  echo "  smtp : Envoie un e-mail via SMTP"
  echo "  open : Ouvre un fichier avec vim"
  echo "  rps: Lance une partie de pierre feuille ciseaux en 3 points"
  echo "  joke: Fait une blague"
}